Virtual-Coffee/virtualcoffee.io

- src/_data/members.js
#32 
I added an if statement that checks whether or not the blog starts with `http` and if it doesn't add the `https://` to correct the path and allow the users blog to be accessed. 
This change was made due to some blog url's not being entered in correctly. This change should fix that.
> Correct blog website URL if needed

- src/members.njk
Issue #48 
If blog was present, the flag beside the member's name said "Available for work!" within an anchor tag. However, if the member did not have a blog, the flag beside the member's name said "Hireable!" within a span tag.
Updated span tag inner text to say "Available for work!"
> Updated 'Hireable' flag to say 'Available for work'

- src/assets/scss/_members.scss
#41 - Layout issue with members with smaller github profile photos
Updated src/assets/css/scss/ _members.scss
- Changed max-width to width:50% for desktop
- Added width: 100% to mobile as a precaution, though not needed.
With a fixed width, a membercard will take up the full desired width instead of determining its width by its contents. This allows for the image to be a standard size and the social media to go all the way to the right edge.
> KLD: Updated membercard from max-width to set width

- src/members.njk
#63 
Removed blog conditional on available for work label and replaced with singular span tag.
Since we are no longer linking to the member/founder's blog, I removed the conditional statement that checks if the member/founder has a blog and replaced that entire conditional block with a singular span tag.
Available for work span tag will still be visible if the member/founder hireable flag is true.
> Removed anchor tag from Available for work label

- src/events.njk
Enhancement addresses issue #62
All changes were to events.njk
Enhancement changes the layout of event cards as outlined in the issue:
* Move date to card header
* Add btn, btn-sm, and btn-secondary classes to the 'Details and RSVP' link to change the display to look like a button.
* Add conditional logic to display event description only when it exists
Previously the date was not highlighted, but it should be because it is usually the main difference from card to card.  The new layout makes the date more prominent.
> Change the layout of event cards to highlight the date in the card header and the 'Details & RSVP' in a button

- package.json
Fixes #95 
I adjusted the `build-preview` script slightly:
```diff
-  "build-preview": "npm build && npm serve"
+  "build-preview": "npm run build && npm run serve"
```
As referred to in the issue I raised, the terminal warns the user:
```plain text
`npm build` called with no arguments. Did you mean to `npm run-script build`?
```
Per [npm's documentation](https://docs.npmjs.com/cli/v6/commands/npm-run-script), `npm run` (which is an alias for `npm run-script`) runs a command from the package's `"scripts"` object. In this case, entering `npm run build-preview` in the terminal was calling the two commands `npm build` and `npm serve`, which the CLI cannot interpret because they're both missing the `run` command. This merge will fix that.
> Fix 'build-preview' command

- src/github.njk
- src/index.njk
Closes #140.
As discussed in the issue ticket, we fix the incorrect link for the GitHub repository in the "Get Involved" section. We do this by checking if `permalink: false` (not the same thing as `not permalink`), and if so, we instead use the `eleventyNavigation.url`. Testing locally, we've resolved the problem!
One issue I'll bring up: do we want to rely on all members of  `collections.homePageBlocksSmall` having an accompanying `data.eleventyNavigation.url` field? I initially chose this method so that I wouldn't modify `github.njk`; however, if we think that there will be future small homepage blocks that aren't parsed by the navigation module, I can instead revise this PR and add some special field to our collection. Let me know what you think!
> Fixes "VC GitHub" link on homepage

- .eleventy.js
- src/_includes/layouts/base.njk
I believe this is because the thank you pages are getting sucked up into the PWA precaching.
> Netlify forms aren't working

- src/_includes/macros/members.njk
If membersite was missing https on github info (`virtualcoffee.io` vs `https://virtualcoffee.io`) the link would be broken. This takes care of that.
> Make sure to use http if missing on website url

- src/_data/members/members/rek990.js
#13
This PR reflects the addition of my (Rebecca Key) LinkedIn profile page to my Member Bio on virtualcoffee.io/members/. This was accomplished by replacing `yourlinkedinUserName` with `rebecca-key` within the `accounts` array. My LinkedIn profile successfully rendered when testing the Member page locally.
My LinkedIn account was added such that my profile is more readily accessible within the community.
> Added LinkedIn account to Member Bio

- src/monthlychallenges/sept-2021/index.njk
- #346 
Adding the end of challenge message to the September 2021 monthly challenge page.
This message will appear at the top of the page where users can click on the next challenge link to go to the new monthly challenge page.
> Adding end of challenge message for sep 2021 file

- src/monthlychallenges/oct-2021/index.njk
Closes #413 
Small repeat ```a``` and ```li``` tag caused a broken link. 
Deleted extra code, tested changes on localhost, and matched other links in that section.
> delete extra li and href to fix Voyagger link

- src/_data/members/members/paceaux.js
Adds profile, according to instructions in [issue 13](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13)
Howdy. I'd like to add my profile to the members page. This is a single file, added to `src/_data/members/members`
I've been active in the slack community for maybe a year now. I figure it's time to commit to it. 
> adds profile information

- netlify/functions/data-members.ts
- types.d.ts
From Typescript Tuesdays episode 9!
In order to improve the custom type definition of the `directory-import` library (see #610), we added some JSDoc improvements, and used type overloading to allow for different shapes of return values (instead of just saying `any`)
> Update typescript definition for `directory import`

- app/routes/index.tsx
Remix [released a new type in 1.6.5](https://github.com/remix-run/remix/releases/tag/remix%401.6.5) called `LoaderArgs`:
> With this change you no longer need to manually define a LoaderData type (huge time and typo saver!), and we serialize all values so that useLoaderData can't return types that are impossible over the network, such as Date objects or functions.
We can make use of that in our typescript routes right now!
- Set `loader` to use `(args: LoaderArgs)`
- Set `useLoader` to use `<typeof loader>`
- Removed `LoaderData` type (no longer needed)
> replace LoaderFunction with LoaderArgs

- app/components/PostList.tsx
- app/components/content/FileIndex.tsx
- closes #684 
Migrate `src/component/FileIndex.js` to typescript.
export `FileListItem` from `PostList` for type-checking
> Typescript conversion: app/component/FileIndex

- app/components/MemberCards.tsx
- styles/_members.scss
Closes #655
Virtual Coffee member's page is growing rapidly. In order to improve the perforamce of the member's page, `loading = "lazy"` and `decoding="async"` were added into the `<img>` tag. Also to keep it uniformed and bit quicker with loading, added `width=100%` and `aspect-ratio:1/1` into the members css section.  
> Adding lazy loading to members page

- app/routes/__auth/login.tsx
Closes #754 
I added a "Register" link to the login form that routes users to the register page.
At the moment there is no way users are able to register for an account from the login page. Adding the link allows them to do so.
By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)
> added register link to login form

- .github/DISCUSSION_TEMPLATE/css-battles.yml
Closes #900 
Adds discussion template for category CSS Battles on Virtual Coffee discussion forums
@danieltott what do you think? 😄 
| creating discussion | discussion look |
|:-------:|-------|
|<img src="https://i.imgur.com/sFgrkrE.png" width="300"> | <img src="https://i.imgur.com/QOqkCku.png" width="300">|
| creating discussion | discussion look |
|:-------:|-------|
|<img src="https://i.imgur.com/JSjjCnx.png" width="300"> | <img src="https://i.imgur.com/XaEAlo0.png" width="300">|
> add category discussion template

- app/routes/__frontend/monthlychallenges/index.tsx
- app/routes/__frontend/monthlychallenges/oct-2021.jsx
- app/routes/__frontend/monthlychallenges/oct-2022.jsx
- app/routes/__frontend/monthlychallenges/sept-2021.jsx
- app/routes/__frontend/monthlychallenges/sept-2022.jsx
Refers to #969 
We have some broken links to our resources — and to some other external links — in our monthly challenges pages and we want to fix them.
Because Preptember (then Hacktoberfest) is coming soon, I prioritized fixing the September (`sept-2021.jsx`, `sept-2022.jsx`), October (`oct-2021.jsx`, `oct-2022.jsx`), and monthly challenges (`monthlychallenges/index.tsx`) pages. Therefore, this PR will not close the issue yet.
This PR fixes the links and changes some other things in the list below:
- Fixed broken links.
- Fixed semantic HTML.
- Fixed typos and minor wordings adjustments.
- Import `LeadText` and `Link`, and applied them to replace `<p className="lead">` and `<a href="">` for internal links.
- Added alert message in the completed challenges.
- [Monthly …
> Fix broken links and typos in monthly challenges, September, and October challenge pages

- app/data/monthlyChallenges/getChallenges.ts
- app/routes/__frontend/monthlychallenges/index.tsx
- app/routes/__frontend/monthlychallenges/oct-2023.jsx
- app/routes/__frontend/monthlychallenges/sept-2023.jsx
Closes #991 
This PR adds Hacktoberfest challenge page to the website.
Changes done here:
- Added challenge page in `oct-2023.jsx`.
- Updated `getChallenges.ts`.
- Set `current: true` to Hacktoberfest challenge in `index.tsx`.
- Removed `current: true` from Preptember challenge in `index.tsx`.
- Added blog posts for Hacktoberfest and Preptember challenges in `index.tsx`.
- Added challenge is complete alert to Preptember challenge.
https://deploy-preview-994--virtual-coffee-io.netlify.app/monthlychallenges/oct-2023
> Feature/update monthly challenge page to Hacktoberfest

- members/members/pedaars.ts
#995 
Add location latitude and longitude to pedaars.ts
Add Hacktoberfest2023 badge to pedaars.ts
used the provided link to search latitude and longitude and updated pedaars.ts with the required location object
> add hacktoberfest 2023 badge and location object to pedaars.ts

- app/components/MemberMap.tsx
Closes #1038
Adds link to popup window on Members page, which scrolls the page to member card.
> add member card link in map marker popup

- .editorconfig
This is a bit of a punt and something I noticed when doing https://github.com/Virtual-Coffee/virtualcoffee.io/pull/1040
The `.editorconfig` file specifies tabs (yay!) as the `indent_style`, however it was strict on the `indent_size` - which isn't required if using tabs.
It also adds the final new line to the `.editorconfig` file, as required in the `.editorconfig` file
I'm a massive tab fanboy, but love a good sized indent of 4 and have this set in my IDE. I was surprised, when opening VirtualCoffee that, despite everything using tabs, it was extremely tight.
After searching my IDE, i realised the `.editorconfig` specified `indent_size = 2` which, considering it is a tab character, should not be needed.
Removing this allows the tab _size_ to be set in an IDE level for user preference …
> Remove `indent_size` from editorconfig

- members/members/raaynaldo.ts
#995 
Update flare, badges, and location on my member page.
PS: I joined last year hacktoberfest last year, but I wasn't part of VC
> feat: update member page

- netlify.toml
Closes #945 
I've:
- Updated existing resources redirects to point to the latest URLs
- Added new redirects for all the resources from when I contributed the Guide to Open Source
I used the deploy preview form the Guide to Open Source PR as a reference for the old URLs: [https://deploy-preview-420--virtual-coffee-io.netlify.app/resources](https://deploy-preview-420--virtual-coffee-io.netlify.app/resources)
I added new redirects and updated existing ones, using the current `netlify.toml` format as a reference
> Add and update redirects for resources pages

- app/api/cms.server.ts
- app/data/monthlyChallenges/getChallenges.ts
- app/data/monthlyChallenges/nov-2023.ts
- app/routes/__frontend/monthlychallenges/index.tsx
- app/routes/__frontend/monthlychallenges/nov-2022.tsx
- app/routes/__frontend/monthlychallenges/nov-2023.tsx
- app/routes/__frontend/monthlychallenges/oct-2023.jsx
Closes #1074 
This PR adds November challenge onto the webpage with details as follow:
- Added `nov-2023.tsx` --> copied and updated from `app/routes/__frontend/monthlychallenges/nov-2022.tsx`.
- Updated `monthlychallenges/index.tsx` with current challenge.
- Updated `data/monthlyChallenges/getChallenges.ts`.
- Added the alert of challenge is complete in `app/routes/__frontend/monthlychallenges/oct-2023.tsx`
Monthly Challenge Page:
https://deploy-preview-1077--virtual-coffee-io.netlify.app/monthlychallenges
November Challenge Page:
https://deploy-preview-1077--virtual-coffee-io.netlify.app/monthlychallenges/nov-2023
October Challenge Page:
https://deploy-preview-1077--virtual-coffee-io.netlify.app/monthlychallenges/oct-2023
> By submitting this pull request, you agree to follow our [Code …
> feature: Add November 2023 Challenge

- members/teams.ts
Closes #1099 
- Remove the previous Monthly Challenge Team Leads from the Monthly Challenge Team Lead team.
- Add the new Monthly Challenge Team Leads (myself and @adiati98) to the Monthly Challenge Team Lead team.
- Remove myself from the (non-team lead) Monthly Challenge team to avoid duplicate badges.
@BekahHW @juliaseid
> Update Monthly Challenge team leads

- app/routes/__frontend/newsletter/issues/2023-02.jsx
- app/routes/__frontend/newsletter/issues/2023-03.jsx
- app/routes/__frontend/newsletter/issues/2023-04.jsx
- app/routes/__frontend/newsletter/issues/2023-10.jsx
- app/routes/__frontend/newsletter/issues/2023-12.jsx
- app/routes/__frontend/newsletter/issues/2024-01.jsx
https://github.com/Virtual-Coffee/virtualcoffee.io/issues/1120
Changed all the links for Nick Taylor's news letter to  https://www.nickyt.co/news
Needed to keep product up to date and not have any dead links.
> updated deprecated links for Nick Taylor's news letter 

- app/data/newsletters.ts
- app/routes/__frontend/newsletter/issues/2024-02.jsx
Closes #1127 
This PR adds February 2024 newsletter to the website and updates the `newsletters.ts`.
https://deploy-preview-1128--virtual-coffee-io.netlify.app/newsletter/issues/2024-02
> docs: Add February 2024 newsletter to the website

- src/content/members/members/bsuraj.ts
https://github.com/Virtual-Coffee/virtualcoffee.io/issues/1240
New profile added
followed the docs and livestrem
> Added - bsuraj.ts

- src/content/members/members/derekjj.ts
- src/content/members/members/zo0o0ot.ts
#13 
This pull request adds zo0o0ot to the members list.
I followed the directions in #13 to make sure I was doing the right work.  I'm also mentoring @pkcnj and I wanted to know the work that they are doing.
Note: I've been participating in Hacktoberfest since 2015, but only since 2023 with VirtualCoffee, so I'm not sure if I'm supposed to have the 2022 badge.
Agreed!
> Adds zo0o0ot

- .tool-versions
Resolves #1265 
This changes the `.tool-versions` file to accurately reflect the versions used in the site build.
I copied the versions referenced in the `package.json` file into the `.tool-versions` file.
> Make .tool-versions file versions match package.json file versions

- src/components/Nav.tsx
fixes the issue: when you click a link in the header navigation, the page navigates but the menu stays open.
> fixes #1234

- src/app/events/page.tsx
Closes #1271 
This PR adds the end time of events to the card headers on the Events page
This change helps event attendees by displaying the duration of all events in a prominent location on the page.
>  feat: Add End Time to Events

- src/content/members/members/victorialo.ts
> add victorialo to members page

- src/content/members/core/bekahhw.ts
relates to #1240 
- update LI profile, personal site URL, and add 24 hacktoberfest badge
> feat: Update bekahhw for hacktoberfest24

- src/app/monthlychallenges/(challenges)/nov-2023/page.tsx
- src/app/monthlychallenges/(challenges)/nov-2024/page.tsx
- src/app/monthlychallenges/(challenges)/oct-2024/page.tsx
- src/app/monthlychallenges/page.tsx
- src/data/monthlyChallenges/NaNoWriMo.ts
Closes #1285 
This PR adds November 2024 challenge (Blogging Challenge) to the website.
**Challenge Homepage**
https://deploy-preview-1286--virtual-coffee-io.netlify.app/monthlychallenges
**Challenge Page**
https://deploy-preview-1286--virtual-coffee-io.netlify.app/monthlychallenges/nov-2024
> feat: Add November 2024 Challenge to the Website

- src/components/Nav.tsx
Hey everyone, I like your community's initiative and wanted to make a small contribution on improving the website. Please let me know if the original implementation was intended for some reason or if you see some problem with my changes. Thanks!
This PR addresses an issue where the navbar's second list (the one with the social links - github, X, youtube ) is announced with 1 link item by screen readers due to the fact that all links are into a single `li` element.
To fix this issue, each link has been added to an individual list item and CSS classes have been adjusted (moved to `ul` element) to maintain the original visuals. As a result, screen readers will now announce the list with 3 items.
Changes are suggested to improve accessibility.
> By submitting this pull request, you agree to …
> fix: convert nav social links to individual list items to improve accessibility

- netlify.toml
Closes #1316 
I have added two redirects so the CFP form and Conference Survey can be shared using VCIO links.
I've used 302 redirects so the links can be reused in future to link to new forms.
> feat: Add redirects to create VCIO URLs for the CFP and survey forms

- src/components/PostList.tsx
#1309
My guess here is the issue is caused by using `path.join` for creating the `slug` value. In `formatFileListItemsForPostList`, we were searching for the string `content/` which might not exist if `path.sep` === `\`.
> Fix file paths on windows

- src/components/MemberMap.tsx
#1400
remove the shadowUrl from the custom map marker icon
The leaflet-shadow-pane class was being rendered along with the custom icon as we are not passing anything into this property it can be removed
> fix: remove the shadowUrl from the custom map marker icon
