Virtual-Coffee/virtualcoffee.io

src/_includes/layouts/base.njk
src/assets/scss/_footer.scss
src/assets/scss/main.scss

A quick refresh of the footer - cleans up some accessibility warnings in lighthouse, and also it looks pretty so I like it

Footer tweaks to address contrast and tap size

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation_template.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question_template.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

I have pirated issue/repo templates and contributing from @tkshill via https://github.com/tkshill/Quarto
I haven't taken a hard look at them - probably needs some refining for our specific repo/use cases

GitHub Powerups

---

src/_data/members/saramccombs.json

Add myself as a member of Virtual Coffee per Issue #13

Add Sara McCombs as a member of Virtual Coffee per Issue #13

---

src/_data/members/mrsantons.json

#13 
Adding myself to virtualcoffee.io members page!
Adding myself into the page of such a great tech community. It's always nice to support others in their journey.

Add mrsantons to members

---

src/_data/members/surajpanchal.json

Added myself to members page

---

src/_data/members/aurelieverrot.json

Issue #13 
Added a json file with my github's profile.
I followed Dan's tutorial :)

Added aurelieverrot to members page

---

src/_data/members/danieltott.json

As per https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13
I tried to follow Dan's instructions and added my json file.

Added dan ott to members page

---

src/_data/members/luciacerchie.json

As per https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13
Added my json file.
Sometimes a developer feels that it's okay to write "Business/Product requirement" in the description. That's fine, but doing so defeats the purpose of this section.
If there is a better explanation as to why the changes were suggested, it's always good to attach a document reference link for that information.
A good "Why" section should explain the reasoning behind any changes.]_

added cerchie to members page 

---

src/_data/members/vanessacor.json

https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13 
I follow Dan's instructions and this my json file.

add vanessa poppe to members page

---

src/_data/members/brandonbrown4792.json

As per https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13
Added brandonbrown4792.json file to be rendered on members page.

Added brandonbrown4792 to members page

---

src/_data/members/kldickenson.json

Adding Karen to the Members' page
Members Page #13
Adding members/kldickenson.json (Karen's GitHub username) per the VC Hacktober Fest workshop.

Members - K Dickenson

---

src/_data/members/dominicduffin1.json

#13 
Add my information for the members page

Add my Github username to member list

---

src/_data/members/needcaffeine.json

Added myself to the members page, per #13.

Add Vic to members page

---

src/_data/members/maylenepoulsen.json

Added Maylene Poulsen to members

---

src/_data/members/nickytonline.json

#13
Added a JSON file with my GitHub profile username so that I appear in the list of Virtual Coffee members.
Just followed the instruction in the linked issue to add myself to the list of Virtual Coffee members.

Added myself as a member of Virtual Coffee.

---

src/_data/members/torianne02.json

#13 
- adds myself (Tori Flu.... Crawford (oops 😅)) to the members page
This was done so that I can be listed on the members page, since I am a very happy member of virtual ☕️

adds myself (torianne02) to members page

---

src/_data/members/ChadStewart.json

#13 Added my profile to the members page.
Sometimes a developer feels that it's okay to write "Business/Product requirement" in the description. That's fine, but doing so defeats the purpose of this section.
If there is a better explanation as to why the changes were suggested, it's always good to attach a document reference link for that information.
A good "Why" …

Adding myself to the members page.

---

src/_data/members/clandau.json

Lucky #13 
Add myself to this wonderful group.

add json file with my username

---

src/_data/members/bryanhealey.json

Adding bryanhealey to memberlist

---

src/_data/members/adiati98.json

#13 
Add member .json file of Ayu Adiati

Add myself as member of Virtual Coffee

---

src/_data/members/chucksmith.json

#13 
Add Chuck Smith to the members page.

Add Chuck Smith's profile

---

src/_data/members/taljjaa.json

#13 
Added myself, Jen Kennedy, username Taljjaa to the Virtual Coffee Member's List 
Followed the instructions on the [issue](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13) to officially add myself to this awesome group! ☕

Added Jen Kennedy to Members List 

---

src/_data/members/mikerogers0.json

#13
Added myself (MikeRogers0) to the Virtual Coffee Member's List.
^^ Looks awesome!
I copied https://github.com/Virtual-Coffee/virtualcoffee.io/pull/52

Adding Mike to Members page

---

src/_includes/macros/members.njk
src/events.njk
src/members.njk

#70 
changed html code structure for member page via making macros

fixed issue#70 - Create membercards macro to simplify members template

---

.eleventy.js
src/assets/scss/_variables.scss
src/monthlychallenges/nov-2020.md

Create a file to track progress of November monthly challenge

Add markdown file for november monthly challange tracking

---

src/monthlychallenges/nov-2020.md

I wanted to add my post to https://virtualcoffee.io/monthlychallenges/nov-2020/ :D 
HUMBLE BRAG: https://www.heroku.com/customers/community-stories < It got listed here.
I think the page is manually built, so I added myself into the HTML. Then updated the table manually.
https://deploy-preview-82--virtual-coffee-io.netlify.app/monthlychallenges/nov-2020/ < Quick preview 👍

Adding Mike's post to Monthly Challenge

---

src/monthlychallenges/nov-2020.md

- adds Tori's "What is CI/CD?" article to the November monthly challenge tally
- I added myself to the HTML and updated the table manually.
- Running totals were also updated manually. 
https://deploy-preview-83--virtual-coffee-io.netlify.app/monthlychallenges/nov-2020/

Adds Tori's post to November monthly challenge

---

src/monthlychallenges/nov-2020.md

- Add Ayu's "Networking & Community" article to the Monthly Challenge
- Rearrange table's order based on total words following this thread: https://github.com/Virtual-Coffee/virtualcoffee.io/pull/83#pullrequestreview-529363261
- I added my post to the HTML and updated the table manually.
- Totals were also updated manually.
https://deploy-preview-85--virtual-coffee-io.netlify.app/monthlychallenges/nov-2020/

Add Ayu's post to Monthly Challenge

---

src/_data/members/meg-gutshall.json

#13 You want my beautiful face on this site. Trust me. 😆

Add Meg as a Member

---

src/monthlychallenges/nov-2020.md

I added my latest blog post rewrite and updated the formatting a bit. I prettied up the markdown per linter specs and alphabetized the top section by member name.
Here's the VSCode extension for the [markdown linter](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) I use. The alphabetization is just because I'm becoming more anal by the second. **ORGANIZATION!!** 😱

Nov Challenge — Meg Blog Post Add & Formatting

---

src/monthlychallenges/nov-2020.md

Not related to any issue
Karen adding her Exercism Teams blog with word count to November's monthly challenge page.

Karen: adding her new blog post to monthlychallenges/nov-2020

---

src/monthlychallenges/nov-2020/nov-2020.json

#91 
Add Ayu's new post **CSS Unit: em** for monthly challenge

Add new post for monthly challenge

---

src/monthlychallenges/nov-2020/nov-2020.json

Kirk's monthly challenge update

---

src/monthlychallenges/nov-2020/nov-2020.json

Issue #91 
Add new posts to the total count via JSON file:
- Kyle's "Automating the pain away" post
- Debra-Kaye's "Navigating the World of Web Development" post
- Meg's "Everyday Inspiration" post and two finished `README`s
Ran in preview mode and all looked good! 👍 Love the new status bar!

November Monthly Challenge Updates

---

src/monthlychallenges/nov-2020/nov-2020.json

#91
Added my latest blog post to the count.

Updated my counts for the monthly challenge

---

CODE_OF_CONDUCT.md
src/forms/report-coc-violation/index.njk
src/forms/report-coc-violation/thanks.njk

Add a form for people to submit CoC violations

Add CoC violation reporting form

---

src/monthlychallenges/nov-2020/nov-2020.json

#91
Adding a new blog to the monthly challenge.
Sometimes a developer feels that it's okay to write "Business/Product requirement" in the description. That's fine, but doing so defeats the purpose of this section.
If there is a better explanation as to why the changes were suggested, it's always good to attach a document reference link for that information.
A good "Why" section should explain the reasoning behind any changes.]_

added a new blog post to novv-2020 json

---

src/monthlychallenges/nov-2020/nov-2020.json

#91 
Ayu add 2 new posts:
- Contributing To An Open Source by A First-Timer (Part 1)
- Contributing To An Open Source by A First-Timer (Part 2)

Add Ayu's new posts

---

src/monthlychallenges/nov-2020/nov-2020.json

Add new post and link

---

src/monthlychallenges/nov-2020/nov-2020.json

#91 
nov-2020.json updated with Karen's new post on her lightning talk.
Update JSON file.

Karen- new post on lightning talk

---

src/_data/members/danieluhl.json

Add yourself as a member https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13
Adds member file `danieluhl.json`

adds danieluhl member file

---

src/monthlychallenges/nov-2020/nov-2020.json

https://github.com/Virtual-Coffee/virtualcoffee.io/issues/91
I wrote a post on RSpec, it's 341 words (I removed the code blocks when I counted it) :D

Adding Monthly Challenge Post (341 Words by Mike)

---

src/monthlychallenges/nov-2020/nov-2020.json

#91 
Ayu adds a new blog post:
"When Should You Start To Write A Blog?"

Add a new blog post for monthly challenge

---

src/monthlychallenges/nov-2020/nov-2020.json

#91 
Glen adds a new blog post "Adventures in Back Channel Job Hunting" (1351 words)

Adding Monthly Challenge Post (1351 words by Glen)

---

src/monthlychallenges/nov-2020/nov-2020.json

#91
Added another Virtual Coffee monthly challenge post of mine to the count.

Added another Virtual Coffee monthly challenge post

---

src/monthlychallenges/nov-2020/nov-2020.json

#91 
I have spoken
This is the way

Add new post

---

src/monthlychallenges/nov-2020/nov-2020.json

#91 
I wrote things! 
Sometimes a developer feels that it's okay to write "Business/Product requirement" in the description. That's fine, but …

added Jen Kennedy to monthly challenge

---

CODE_OF_CONDUCT.md

fixed broken coc report form link in COC

---

src/monthlychallenges/nov-2020/nov-2020.json

Kirk's last submission monthly challenge

---

src/monthlychallenges/dec-2020/dec-2020.json
src/monthlychallenges/dec-2020/index.11tydata.js
src/monthlychallenges/dec-2020/index.njk
src/monthlychallenges/nov-2020/nov-2020.json

Fixes #127
This commit adds a data structure for the December monthly challenge and the first version of the page.

new: create the december 2020 challenge page

---

src/monthlychallenges/dec-2020/dec-2020.json

Add pairing session to December's monthly challenge page

---

CONTRIBUTING.md

#132
_Preferred code style_ and _commit message conventions_ sections removed from Table of Contents in CONTRIBUTING.md to match document body.

Update CONTRIBUTING.md Table of Contents

---

src/monthlychallenges/dec-2020/dec-2020.json

Added Colleen and Nick pairing session

---

src/monthlychallenges/dec-2020/dec-2020.json

#130 Add December pairing session!
We had a mini pairing session debugging JavaScript 🎉

Adding session for Mike & Laura

---

src/monthlychallenges/dec-2020/dec-2020.json

#130 
Adding 4 pomodoros-worth of pairing sessions with Belle & Courtney.

Adding pairing sessions for Courtney & Belle

---

src/_data/members/calendee.json

N/A
Just adding me as a member per  #13.
N/A

feat: add new member calendee

---

src/monthlychallenges/dec-2020/dec-2020.json

Adding my last three pairing sessions to December's monthly challenge!
ref #130

Add Dan’s three latest pairing sessions

---

.eleventy.js
package-lock.json
package.json
src/_includes/layouts/base.njk
src/assets/favicon/site.webmanifest

#134 
Changes for adding PWA support into site by using eleventy-plugin-pwa
- Modified manifest file as per https://web.dev/add-manifest/ guidelines which enables to install as native app.
- Register service worker generated by workbox in base.njk file to cache files generated in build. 
Please refer below screenshots:
- Install Button in browser
- After Installing app (on windows machine)
- Once you browse site on mobile device it will give prompt to add its to home screen.

Added PWA support using eleventy pwa plugin

---

src/monthlychallenges/dec-2020/dec-2020.json

More pairing actvities

---

src/monthlychallenges/dec-2020/dec-2020.json

Add Bekah & Dominic pairing session to Monthly Challenge page

---

src/_data/members/gantlaborde.json

add Gant Laborde

---

src/monthlychallenges/dec-2020/dec-2020.json

Add Bekah and Dominic pairing session on Dec 22

---

src/_data/members/s-blais.json

add s-blais to /members/

---

src/_includes/layouts/podcast.njk
utils/imgix.js

Use imgix to allow for auto formatting and resizing for podcast images

use imgix for podcast images

---

src/_data/members/juliaseid.json

Add juliaseid to members

---

src/monthlychallenges/jan-2021/jan-2021.json

Kirk jan 2021 challenge

---

src/monthlychallenges/jan-2021/jan-2021.json

#179 
I'm still working through the main resource I used, but these are a couple of others I referred to that I recommend.

Dominic: First two resources from January month of learning

---

src/_data/members/matthew-dean.json

Related to #13 - Add myself as a member

---

src/_data/members/AmyShackles.json

#13 
- Adds AmyShackles.json to src/_data/members
- Followed instructions listed in the linked issue

Add AmyShackles to members

---

src/_data/members/memberData.json
src/_data/members/members.json
src/_data/members/tomcudd.json

#13 
Adding members/tomcudd.json per instructions in issue
Copy paste

Adding tomcudd to members

---

src/monthlychallenges/mar-2021/index.njk

Get job ready -> Monthly challenge draft

WIP Draft of March Challenge

---

src/_data/members/memberData.json
src/_data/members/members.json

Adding crisbnp to members page
Adding crisbnp to members.json file

Adding crisbnp to members

---

src/_data/members/kfairris.json

#13 
added myself to the members list - kfairris.json
Why?  Because I want to be included.  😄

added myself - Kenny Fairris

---

src/_data/members/members.json

#13  
Adding Adam Abundis (abuna1985) to the member's list
I followed the instructions on issue #13

Added adam abundis - abuna1985 to members list

---

src/_data/members/memberData.json
src/_data/members/members.json

Adding self to members json page

---

src/_data/members/memberData.json
src/_data/members/members.json

#13 
Adding myself (Enrique Hilst) to the virtualcoffee.io members page.

Add ehilst515 to members

---

src/_data/members/memberData.json
src/_data/members/members.json

#13 
Added myself to the members page

add cafloyd to members page

---

src/_data/members/members.json

#13
Added "LincolnFleet" to members.json
'cuz I wanna hang with the cool kids

Add LincolnFleet to members

---

src/newsletter/issues/2021-04.njk

Add the latest issue (April) using the format from the past issues.
Created .njk file for April and formatted it accordingly.

VC April Newsletter

---

src/_data/members/members.json

#13 
Added myself to the members list.
So I can join the community :)

added username

---

src/membership.njk

Add an optional field for a member's twitter user!
Also enhanced the github/twitter inputs to help make it clear what info we're looking for.

Add twitter handle to membership form

---

src/_data/members/members.json

#13 
Added my username to the .json

Added danielcobo to members

---

src/_data/members/memberData.json
src/_data/members/members.json

Adding AlexVCS to members page.

---

src/_data/members/members.json

#13 
Sometimes a developer feels that it's okay to write "Business/Product requirement" in the description. That's fine, but doing so defeats …

update members.json to add Michael Honey-Arcement

---

src/newsletter/issues/2021-05.njk

May Newsletter

---

src/_data/members/members.json

Adds Simon Prickett

---

src/_data/members/members.json

Followed instructions in Add yourself to Members page (Issue #13 https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13)
Added barbaralaw to members.json

added user barbaralaw

---

src/monthlychallenges/june-2021/index.njk

Add new challenge

---

src/_data/members/members.json

added myself to members.json

---

src/_data/members/members.json

add bmeverett to members.json

---

src/_data/members/members.json

added abbeyperini to the end of the members.json
I wanted to be shown as one of the members.

add abbeyperini

---

src/_data/members/members.json

add zoolglon to members list 

---

src/monthlychallenges/july-2021/index.njk

#270 
Add a list of tips and link to Loom demo of demoing to July challenge page.

Add tips and demoing Loom to July challenge

---

src/newsletter/issues/2021-07.njk

#267 
Add July 2021 newsletter

Add July newsletter

---

src/_data/members/members.json

New members #13 
Added my github username on the list of members.
By following the instructions on the linked issue; updating the members.json file under the path src/_data/members/members.json.

added ntinosng to members.json

---

src/_data/members/members.json

adding myself as a member re instructions in #13

add davidalpert as a member

---

src/podcast/0303-ayu-adiati.njk

Add Ayu's episode!!

---

src/_data/members/members.json

#13 
One-line addition to the very end of the members' json file to include my GitHub username!
Attended yesterday's virtual coffee hour. Had a blast. Would love to continue to be part of this community :)

Added my username to the members list.

---

src/monthlychallenges/aug-2021/index.njk

[#281](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/281)
Create a August folder on monthly-challenges
Create an `index.njk` on it and add the content based on the monthly-challenge docs and comments

add august-monthly challenge

---

src/_data/members/members.json

#13 
Add myself to the members page after becoming a member!
I attended my first Virtual Coffee today and signed up for membership afterwords, looking forward to attending more afternoon meetups. :)

Add my GitHub username to the list

---

src/newsletter/issues/2021-08.njk

#282 
Add August 2021 newsletter

Add August newsletter

---

src/monthlychallenges/apr-2021/index.njk
src/monthlychallenges/dec-2020/index.njk
src/monthlychallenges/feb-2021/index.njk
src/monthlychallenges/jan-2021/index.njk
src/monthlychallenges/july-2021/index.njk
src/monthlychallenges/june-2021/index.njk
src/monthlychallenges/mar-2021/index.njk
src/monthlychallenges/may-2021/index.njk
src/monthlychallenges/nov-2020/index.njk

#283 
Added the challenge-completed alert to all completed challenges.

Added challenge-complete alert to completed challenges

---

src/newsletter/index.njk

Fixes for Issue #308
This is my first PR to open source
This PR made some changes to the newsletter section specifically the text on index.njx (src>newsletter>index.njx). Prior to this PR the documentation was addressing that the newsletter wasn't active. I made the change in the documentation describing that the newsletter is now active.

Tense changed in Newsletter copy

---

src/index.njk

Fix: Spacing between code line.

---

src/_data/members/members.json

adding myself as a member re instructions in #13

Added my github name to members.json

---

src/newsletter/issues/2021-09.njk

#323 
Add September 2021 newsletter

Add September newsletter

---

src/_data/members/members.json

Followed steps here:
I added my username to the members list.
Followed steps in https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13

add awildstone to members list

---

.env.example
src/_data/members/members.json

added danieljanderson

---

CONTRIBUTING.md

closes #343 
Changed the capitalization in Contributing.

Correct capitalize in Contributing

---

src/_data/members/members.json

#13 
Added my GitHub username to the end of [`src/_data/members/members.json`](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/src/_data/members/members.json)
Changes made to be part of Virtual Coffee.

usernameAdd

---

src/_data/members/members.json

None
Updated Members.json to include self.

Added Self to Members.json

---

src/_data/members/members.json

This PR adds Lohit Yarra (lohityarra) to the member list of virtualcoffee.io.
lohityarra was added to members.json

Add lohityarra to members.json

---

src/monthlychallenges/oct-2021/index.njk

- closes #345 
This pull request provides the details for the October 2021 monthly challenge page.
N/A

2021 October challenge

---

src/_data/members/members/thacherhussain.js

Github Issue: #13 
Added my profile to the members section
Followed the instructions in the issue, added a new file for my profile

added thacherhussain member file

---

src/_data/members/members/loganom.js

- #13 
Added my user profile data
Followed instructions

Create loganom.js member profile js file

---

src/_data/members/members/teezzan.js

#13 
I added links to my online profiles and updated my name.
Not much to say. Basic typing stuff, you know.

Updated teezzan.js member details

---

src/_data/members/members/jenkens-dev.js

- #13 
Was already a member so updated my member js file to include my LinkedIn
Followed Dan's great demonstration

Update member information for Jen Kennedy to include linkedin profile

---

src/_data/members/members/lohityarra.js

- #13 
Added some socials to it.
Followed clear instructions from Dan.

Updated lohityarra.js

---

src/_data/members/members/lsparlin.js

- #13 
Add Lewis Sparlin member to member page. First PR of Hacktoberfest!
Followed add Add your profile to members page directions

Add lsparlin (Lewis Sparlin) memeber data

---

src/_data/members/members/ClJarvis.js

#13  updating profile
updated profile 
Sometimes a developer feels that it's okay to write "Business/Product requirement" in the description. That's fine, but doing so defeats the purpose of this section.
If there is a better explanation as to why the changes were suggested, it's always good to attach a document reference link for that information.
A good "Why" section should explain the reasoning behind any changes.]_

updating my member information

---

src/_data/members/members/jdwilkin4.js

-#13
Adding my user profile data

Create jdwilkin4.js member profile js file

---

src/_data/members/members/cassiel257.js

Creating a VC user profile for the website.
Issue #13 
Adding my user information to the Virtual Coffee site.
Hacktoberfest Kickoff interactive pull requests session.
_[This section explains why the above …

Create cassiel257.js for TiffanyU

---

src/_data/members/members/spike.js

Add your profile to our Members Page! #13 
Adding my bio and social links to virtual coffee members page.
I followed the instructions and code along with the Virtual Coffee Hacktoberfest Kickoff Event

add my bio and social links

---

src/_data/members/members/mccurcio.js

Matt Curcio 
Striving Data Science/Engineer
Metro Boston, MA
Adding Matt Curcio as member of VC
na
na

Adding Matt Curcio as member of VC

---

src/_data/members/members/arvinf07.js

-#13
Created new member js file so that I can appear on members page!
Copied template and filled info. Nice and simple

created new member file

---

src/_data/members/members/secondl1ght.js

Added a few new links to my profile on members page!

Update profile info

---

src/_data/members/members/nickytonline.js

#13
I updated my existing member profile with the new profile information available to members.

Update member Nick Taylor's info

---

src/_data/members/members/secondl1ght.js

Sorry I realized I wanted a different mainURL so I made another change

Update profile again

---

src/_data/members/members/adiati98.js

#13 
Update Ayu Adiati's info on the member page:
- Update name
- Add mainURL
- Add accounts

Update Ayu Adiati's member info

---

src/_data/members/members/sadiejay.js

- #13 
- Adds member file
- Added required github username and markdown for bio.

Adds sadiejay member file

---

src/_data/members/members/redapy.js

#13
added myself as a VC member
instructions has been followed.

create redapy.js member profile.

---

src/_data/members/members/rreiso.js

#13
Created rreiso.js file in members folder.

Add Ruta R to members page

---

src/_data/members/members/_EXAMPLE.js
src/_data/members/members/sadiejay.js

#396 
Truncated the affected member's biography, commented out original. This is the short term fix. Long term fix coming in separate issue.

Truncate sadiejay's bio. (#396)

---

src/monthlychallenges/aug-2021/index.njk

#387
I've added an end of challenge message for the august challenge and linked to the October challenge .
followed the suggested solution.

add an end message to the august challenge

---

src/_data/members/members/nicoolel.js

#13 
Added my user profile data
Followed Dan's instructions

create nicole lee's member profile

---

src/_data/members/members/regromrob.js

#13 
Add my profile information to update members page.
Followed instructions given

add Regina's profile to member page

---

src/_data/members/members/crislanarafael.js

Adding Crislana Rafael to member's page per issue #13

Add Crislana Rafael's (crislanarafael) member data

---

src/newsletter/issues/2021-10.njk

#403  
Add October 2021 newsletter.

Add October newsletter

---

src/_data/members/members/aureliefomum.js

This is my info for Issue #13
I created a duplicate of the example.js file and added my GitHub username to it.
Followed step-by-step instructions in the issue's ReadMe.

Please add Aurelie Fomum to Virtual Coffee's members' page

---

src/_data/members/members/norafergany.js

#13 
Added norafergany profile to members
Provided github username and selected optional overrides

Add norafergany member profile

---

src/_data/members/members/magsol.js

No active linked issue.
Followed the contribution instructions given on the main Virtual Coffee GitHub organization page.
Added my membership information since I've now attended two Virtual Coffee meetings :)

Created a membership file for myself.

---

src/_includes/layouts/podcast.njk
src/podcast/0401-jessi-shakarian.njk

Add jessi's episode!

---

src/newsletter/issues/2021-11.njk

- closes #467
Add November 2021 November Newsletter to the website.
Following the steps from the issue description.

Add November Newsletter

---

src/podcast/0405-suze-shardlow.md

add suze episode

---

src/_data/members/members/carrollsa.js

This is my first fork/pull request. Please let me know if there's anything I missed. Thanks for the great guide!

add profile

---

src/monthlychallenges/dec-2021/index.njk

Closes #482 
This adds the new page for the December Monthly challenge.
Thank you to Abbey and Kirk for creating the content.  I wrote up the page itself quite quickly and it needs a thorough review.  I think we could maybe use a few more details regarding hashtags and participation, but that can come in a subsequent PR if that is alright.
I would value input from anyone.  I want to callout these folks since they have contributed to this already.
- @tkshill 
- @abbeyperini 
- @BekahHW 
- @aurelie-verrot 
https://github.com/Virtual-Coffee/VC-Contributors/discussions/227 here is the initial discussion for these changes.  This was done as part of the regular release cycle for the monthly challenge team.
> By submitting this pull request, you agree to follow our [Code of …

Add new page for December Challenge

---

src/_data/members/members/jjshanks.js

Add jjshanks to members

---

src/_data/members/members/jasmine582.js

Created jasmine.js member profile

---

src/newsletter/issues/2021-12.njk

Closes #486 
Add December 2021 newsletter.

December newsletter

---

src/_data/members/members/lsparlin.js

#13 
I've updated a few of my online profiles and my personal domain, so I updated my member data 😄 
> By submitting this pull request, I agree to follow the [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

Some updates to Lewis Sparlin member profile

---

src/_includes/layouts/base.njk
src/index.njk

#491 
- Fix links to *Code of Conduct* and *Our Members* pages from *All Things Virtual Coffee* section on the homepage.
- Fix link to *About* page at navbar.

Fix links to Code of Conduct, Our Member and About

---

src/resources/virtual-coffee/slack-channel-guide.md

#497 
Update Virtual Coffee's Slack channel guide to current channels.

Update Virtual Coffee Slack Channel Guide

---

src/monthlychallenges/dec-2021/index.njk
src/monthlychallenges/jan-2022/index.njk
src/monthlychallenges/nov-2021/index.njk
src/monthlychallenges/oct-2021/index.njk

Resolves #499 
This creates a new page on the VCIO site for the January 2022 monthly challenge.
Additionally, I added a banner to several previous months to indicate that those challenges are complete.
Requested Reviews:
- @BekahHW - as the boss
- @aurelie-verrot - as the creator of the documentation for this month's challenge
This was done as part of the monthly process of supporting our community challenges.

Add challenge page for jan 2022

---

src/_data/members/members/SNikhill.js

- #13 
Adding my profile ([SNikhill](https://github.com/SNikhill)) to the member's list.
The above changes were done based on the instructions mentioned in the introductory/welcome email I received.

chore(#13): add SNikhill as member

---

src/newsletter/issues/2022-01.njk

Closes #503 
Add January 2022 newsletter.

January 2022 newsletter

---

src/_data/members/members/HDreikorn.js

#13 
Adding HDreikorn to members.
Followed steps in issue #13 

adding HDreikorn to members

---

.github/workflows/monthly-challenge-issue.yml

Automate adding an issue for the new monthly challenge to the site

Add action for monthly challenge issue

---

src/_data/members/members/lauralangdon.js

Adding myself to the members list

---

src/monthlychallenges/feb-2022/index.njk

closes #511 
I added the February Challenge: Pairing, to the VC site.
- I followed the steps suggested in the issue description.
- I skipped the Theme and Goal parts and deleted the "How it Works" part.
- I kept the ''Who can participate?'' part and the "What if I need help" with small changes to match the current challenge.
- I added the link to create a cohort.

add the February challenge 2022

---

src/newsletter/issues/2022-02.njk

Closes #519
Add February 2022 newsletter to the website.

February 2022 newsletter

---

src/_data/members/members/VAggrippino.js

#13 
Add VAggrippino to members
I created the new JS file and added or updated my info.
👍

Add VAggrippino to members - #13

---

src/_data/members/members/niklasfyi.js

#13 
Adding myself as a new member

Add niklasfyi as new member

---

src/newsletter/issues/2022-03.njk

Closes #534 
- Add March 2022 newsletter to the website.

Add March 2022 newsletter

---

.prettierrc.json

Removed the Nunjucks prettier configuration as Remix does not use Nunjucks.
Relates to #544

Removed njk override in prettier config

---

src/newsletter/issues/2022-04.njk

Closes #551
- Add April 2022 newsletter to the website.

Add April 2022 newsletter

---

src/_data/members/members/rhdeck.js

#13
Add @rhdeck to members page
Following instructions on issue #13

Add rhdeck to members

---

app/components/MemberCards.jsx

Closes #559. 
The member cards use `href="{member.mainUrl}"` causing the URL to direct to https://virtualcoffee.io/"member.mainUrl". Instead it should use the the actual `mainUrl` as in `href={member.mainUrl}`.
Changed `href="{member.mainUrl}"` to `href={member.mainUrl}`. 
https://github.com/Virtual-Coffee/virtualcoffee.io/blob/b7d1d5d91d16ae1106b3671bb9f7f94fd6215b73/app/components/MemberCards.jsx#L41
I do! :100:

Fix string to `member.mainUrl`

---

members/members/SafetyVest2789.js

Please add profile to members.

Add my profile to members

---

app/routes/resources/virtual-coffee/join-virtual-coffee.mdx

* Delete link to meetingplace
* Fix h2
Closes #568 
- Change intro to pausing membership
- Delete the link to meetingplace because we won't use it anymore.

Change intro of Join Virtual Coffee section to pause new membership

---

app/data/monthlyChallenges/getChallenges.js

Add may challenge

---

app/routes/resources/virtual-coffee/get-involved/paths-to-leadership.mdx

n/a
- corrected spelling errors
- updated capitalization/punctuation consistency
- added link to Non-Violent Communication guide from CNVC.org

Correct typos on Paths to Leadership

---

app/data/newsletters.js
app/routes/newsletter/issues/2022-04.jsx
app/routes/newsletter/issues/2022-05.jsx

#575 
- Add May 2022 newsletter to the website.

Add May 2022 newsletter

---

app/data/monthlyChallenges/getChallenges.js
app/routes/monthlychallenges/june-2022.jsx
members/members/raeshelle-rose.js
members/teams.json

closes #580 
- I Followed the instructions for [creating monthly challenge pages](https://github.com/Virtual-Coffee/virtualcoffee.io/#monthly-challenges)
- I used the content of the [May challenge 2021](https://virtualcoffee.io/monthlychallenges/may-2022), with some small changes

add june monthly challenge 2022

---

app/data/newsletters.js
app/routes/newsletter/issues/2022-06.jsx

Closes #589
- Add June 2022 newsletter.

Add June 2022 newsletter

---

app/routes/resources/virtual-coffee/get-involved/coffee-table-groups.mdx

Issue #581
- update Coffee Table Group definition
- add Coffee Table Group Leader definition
- discussion with coffee table group leaders

documentation: coffee table group definitions

---

members/members/klezi10.js

Adding myself on the members list

---

app/data/monthlyChallenges/getChallenges.js
app/routes/monthlychallenges/july-2022.jsx

Closes #594 
I added a new monthly challenge for July 2022
Every month virtual coffee has a new monthly challenge

Create a new July 2022 challenge

---

app/data/newsletters.js
app/routes/newsletter/issues/2022-07.jsx

Closes #601 
- Add June 2022 newsletter.

Add July 2022 newsletter

---

members/members/ramonh.js

Hello! Thanks again for the invite to join Virtual Coffee! Here's my member PR :)

Add ramonh

---

app/data/monthlyChallenges/getChallenges.js
app/routes/monthlychallenges/aug-2022.jsx

Closes #605 
I added a new monthly challenge for August 2022.
- I followed the instructions for [creating monthly challenge pages](https://github.com/Virtual-Coffee/virtualcoffee.io/#monthly-challenges)
- I used the content of the [Aug 2021](https://virtualcoffee.io/monthlychallenges/aug-2021) challenge.

Added August 2022 Monthly Challenge

---

app/data/newsletters.js
app/routes/newsletter/issues/2022-08.jsx

Closes #607 
- Add the August 2022 newsletter.

Add August 2022 newsletter to website

---

README.md

Closes #596 
- Add a note to view a page on localhost when encountering `TimeoutError - Task timed out after 10.00 seconds`.

Add note to preview page on localhost in README

---

app/routes/resources/virtual-coffee/guide-to-vc.mdx
app/routes/resources/virtual-coffee/slack-channel-guide.mdx

Closes #613 
- Add new channels to the VC Slack Channel Guide page.
- Add Coffee Tables to VC events on the Guide to VC page.
- Add a co-working section on the Guide to VC page.
- Edit volunteering at VC, contributing to VC, and lightning talk sections on the Guide to VC page.
- Add proper links.
- Add steps to join events and co-working room.

Update "Guide To VC" and "VC Slack Channel Guide" pages

---

members/members/jasmine582.js

Updated linkedin username

---

app/routes/resources/open-source/git-101.mdx

Closes #628 
In the [Git & GitHub 101](https://virtualcoffee.io/resources/open-source/git-101) page:
- Add "Resolve conflicts" section.
- Tweak wordings in the [Add and commit changes](https://virtualcoffee.io/resources/open-source/git-101#add-and-commit-changes) section.
- Edit and update the [Fetching upstream changes](https://virtualcoffee.io/resources/open-source/git-101#fetching-upstream-changes) section.
- Edit and update the [Synchronizing changes locally](https://virtualcoffee.io/resources/open-source/git-101#synchronizing-changes-locally) section.
- Tweak wordings in the [Push changes](https://virtualcoffee.io/resources/open-source/git-101#push-changes) section.
- Edit the [Synchronous collaboration](https://virtualcoffee.io/resources/open-source/git-101#synchronous-collaboration) …

Update Git  & GitHub 101 page

---

app/data/newsletters.js
app/routes/newsletter/issues/2022-09.jsx

Closes #632 
- Add the September 2022 newsletter.

Add September 2022 newsletter to website

---

app/routes/resources/open-source/git-101.mdx
app/routes/resources/open-source/maintainer-guide.mdx

- closes #629 
In the [Documentation](https://virtualcoffee.io/resources/open-source/maintainer-guide#documentation) section:
- Remove the first point in The Contributing Guide section.
- Tweak the second point in The README section.
In the [Resolve colflicts](https://virtualcoffee.io/resources/open-source/git-101#resolve-conflicts) section on Git & GitHub 101:
- Fix the ul format as attached below.

Edit the Documentation section on Maintainer Guide

---

members/core/bekahhw.ts

Update profile with Hacktoberfest badge

---

members/members/alvarosanchez.ts

hacktoberfest badge and flare added

---

members/members/thegrumpyenby.ts

Add profile for thegrumpyenby

---

members/members/ClJarvis.ts

Issue  #643
I added a badge to my profile and added flare.

I added my badge and flare to profile.

---

members/members/adiati98.ts

* Add flare
* Edit Hashnode's username
#643 
- Add Hacktoberfest 2022 badge to Ayu's member profile.
- Add flare
- Edit Hashnode's username.

Add Hacktoberfest 2022 badge to profile

---

members/members/JesseRWeigel.ts

Added 'Hacktoberfest2022' to badges
#643 
add badge

add hacktoberfest2022 badge

---

app/data/newsletters.js
app/routes/__frontend/newsletter/issues/2022-10.jsx

Closes #644 
- Add the October 2022 newsletter.

Add October 2022 newsletter to website

---

members/members/rmirville.ts

* #13 
* #643 
In today's episode of Virtual Coffee, Raynald makes a guest appearance as a pull-requester! He's vying for a spot on the list of Virtual Coffee members. Will Raynald get to see his face on the community page? Find out, after these review messages!

feat: Add Raynald to members

---

members/members/muckitymuck.ts

#643
Added personal info for Andrew Goldstein (muckitymuck).  new file under Members folder

personal info Andrew Goldstein (muckitymuck.ts)

---

members/members/LincolnFleet.ts

Signed-off-by: Travis Martin <travisemerymartin@gmail.com>
https://github.com/Virtual-Coffee/virtualcoffee.io/issues/643
Add Hacktoberfest badge, linkedin username, and profile mask
Face => keyboard => wiggle wiggle wiggle
(very slight data changes on members file)

Add badge and data for LincolnFleet [Travis Martin]

---

members/members/AlexVCS.ts

#643 
Added the Hacktoberfest 2022 badge to Alex's member profile.
Because 🎃

added the Hacktoberfest 2022 badge :)

---

app/components/DisplayHtml.tsx
app/components/MemberCards.tsx
app/svg/Book.tsx
app/svg/Codenewbie.tsx
app/svg/Dev.tsx
app/svg/GitHub.tsx
app/svg/HashNode.tsx
app/svg/LinkedIn.tsx
app/svg/Medium.tsx
app/svg/Polywork.tsx
app/svg/Twitch.tsx
app/svg/Twitter.tsx
app/svg/VirtualCoffeeFull.tsx
app/svg/VirtualCoffeeFullBanner.tsx
app/svg/Website.tsx
app/svg/YouTube.tsx
members/types.ts

#660 
Convert memberCard.jsx into memberCard.tsx.
Convert all icon files into tsx.

refactor(memberCard): convert memberCard and icons to ts. closes #660

---

members/members/JoeKarow.ts
members/teams.ts

#643 - The Party Issue
Hacktobering.

Badge time!

---

members/members/CodingatTiffanys.ts

- #13
- add myself, CodingatTiffanys, to the members folder in VC 
- to be listed as a member of VC and also complete any other associated PR's

add tiffany pena to members

---

members/members/DavidRod1865.ts

Issue #13 
Issue #643 
I needed practice doing Open Source and this was good practice.

Added David Rodriguez to Member Page and Added Hacktoberfest Flare

---

members/members/aishwaryamali.ts

#13 
#643
- adding aishwarya-mali to member profile
- adding hacktoberfest badge

add aishwarya-mali member profile and hacktoberfest badge

---

members/members/jdwilkin4.ts

#13 
#643 
Here are the changes made to my profile:
- adding my devto profile link
- added circle flare to profile image
- added hacktoberfest badge 
I just felt like adding more of my writing profiles to the site. 😄 

updating jdwilkin4 member profile and adding hacktoberfest badge

---

members/members/chaos986.ts

#643 
Added Hacktoberfest 2022 badge and made explicit bio information vs pulling from GitHub.
Open source practice and excuse to hang out with @AmyShackles . 

edited member profile

---

members/members/nickytonline.ts

Relates to #643
Added the Hacktoberfest 2022 badge to my profile.

chore: added my Hacktoberfest 2022 to my profile

---

members/members/megGutshall.ts

Add Hacktoberfest 2022 badge

---

app/util/cmsimage.ts

Closes #689 
- Converted file to TypeScript.
- Created type for input Props.
- Imgix's `params` are [quite numerous](https://docs.imgix.com/apis/rendering), so the additional passed params are typed as `Record<string, any>`

Convert `cmsimage.js` to Typescript

---

members/members/annakimdev.ts

Issue #13 
Issue #643 
I created annakimdev.ts to add my profile to the members page.
I also added Hacktoberfest2022 badge.
Thank you for the clear steps and comments!

add annakimdev as a member per Issue #13 and Hacktoberfest2022 badge #643

---

CONTRIBUTING.md
README.md

Closes #699 
- Update `CONTRIBUTING.md`:
- Change the "Local development" title to "Setting Up Local Environment To Work On Issues" in .
- Add bullet point with how to create new branch.
- Update `README.md`:
- Add bullet points to "Working On The Site" section with the links to `CONTRIBUTING.md` and our open source resources on the website.
- Minor tweaks and fix punctuations.

Update CONTRIBUTING and README files

---

app/data/monthlyChallenges/getChallenges.ts

Fix for a bug I introduced merging in #698 - Remove default of 0 for limit

Fix challenge bug

---

members/members/radturkin.ts

#13 
added rad to members list
rads new in town

Add Rad to members

---

members/members/carmenkolohe.ts

#643 
Add Hacktoberfest2022 to badges array in member file.
Participate in Hacktoberfest

add hacktoberfest badge

---

members/members/sadiejay.ts
members/teams.ts

#643  
I've made changes to my member profile including:
- added a profile mask
- added flare
- added "notetaker" badge
Participating in Hacktoberfest! :)

Update member profile for sadiejay

---

CONTRIBUTING.md

Closes #707
Update `CONTRIBUTING.md`:
- Fix links on the Table of Content.
- Fix typos.
- Minor tweaks.
- Fix headings to follow semantic HTML.

Fix links on Table of Content in CONTRIBUTING.md

---

members/members/dominicduffin1.ts

#643 
I have added the Hacktoberfest badge to my profile, chosen a mask, and updated my links.

Update member profile for Dominic Duffin

---

members/members/radturkin.ts

rad gets a badge

---

members/members/lsparlin.ts

#643 
Add `Hacktoberfest2022` badge to member lsparlin

lsparlin add Hacktoberfest2022 badge

---

app/util/createMetaData.server.ts
app/util/socialimage.ts

- closes #692 
Migrate `app/util/socialimage.js` to typescript with signature Prop type.
Add jsdoc function documentation

Typescript conversion: app/util/socialimage

---

app/components/HomePageBlock.tsx
app/components/UndrawIllustration.tsx

- closes #683 
Convert `HomePageBlock` component to typescript
- Add Home Page Block prop type 
- export and use `UndrawIllustrationName` from `UndrawIllustration` component

Typescript conversion: app/component/HomePageBlock

---

members/members/abuna1985.ts

#643 
Add Flare, Social links (LinkedIn, Twitter, Dev), and Hacktoberfest2022 badge to member Adam Abundis

Added flare, social links, and Hacktoberfest badge to member Adam Abundis

---

members/members/YolandaHaynes.ts

#643 
Updating profile for Hacktoberfest2022

updated profile for hacktoberfest2022

---

app/components/PodcastSubscribe.tsx

Closes #680 
Converted file from `jsx` to `tsx`
Paired with @danieltott 

Converted `PodcastSubscribe` file to tsx

---

app/root.tsx

Closes #729 
Updated the app/root file from jsx to tsx. 
Added a new type definition in order to have easier readability of the code. 

convert app/root from jsx to tsx

---

app/util/http.ts

Closes #690 
Convert `https.js` to TypeScript

convert `http.js` to typescript

---

members/members/jamaalbrown.js

##Linked Issue
#13 
Adding my profile to the Virtual Coffee Website.
I've been a part of Virtual Coffee since earlier this year. Just now getting around to adding my profile to the website!

Add jamaalbrown(myself) to the members

---

members/members/dapoadedire.ts

Add Dapo Adedire

---

app/routes/__frontend/resources/developer-health/index.mdx
members/members/chaos986.ts

#673 
I made a new page and pasted in text from slack and videos from YouTube. 
I am still new to Markdown and React.  
I previewed nothing. 
This could break prod. 

Added new page for Developer Health resources.  Starting with "Burnout"

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/nov-2022.jsx
yarn.lock

Nov challenge page

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2022-11.jsx

#742 
- Add November 2022 newsletter.

Add November 2022 newsletter to the website

---

members/members/jamaalbrown.ts

#13 
I have changed my member javascript file to typescript to be consistent with the rest of the members files
I noticed that my profile wasn't being displayed on the website. When I looked at the code I had submitted in pull request #737  I saw I had submitted a .js file instead of a .ts file. I'm opening this pull request to fix that

Replace jamaalbrown.js with jamaalbrown.ts

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/dec-2022.jsx

Closes #750 
Created the challenge page for December (Creative Community Challenge), added it to the getChallenges.ts file
To prepare for December's monthly challenge.

created the challenge page for December, added it to the getChallenges.ts file

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2022-12.jsx

Closes #775 
- Add November 2022 newsletter.
- Update ` newsletters.ts`. 

Add December 2022 newsletter to the website

---

app/routes/__frontend/events/index.jsx

Closes #752 
- Add "Recorded Events" section to the Events page.

Update events page with recorded events section

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/jan-2022.jsx
app/routes/__frontend/monthlychallenges/jan-2023.jsx

Add Jan challenge

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-01.jsx

Closes #790 
- Add January 2023 newsletter

Add January 2023 newsletter

---

app/routes/__frontend/resources/virtual-coffee/guide-to-vc.mdx

Closes #794 
- Update coffee table events by removing the non-active ones and add the new ones.

Update coffee table events

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/feb-2023.jsx

Add Challenge page

---

app/routes/__frontend/monthlychallenges/feb-2023/index.jsx

- closes #803 
This will close issue 803. Updating resume review date.

updated event date for resume review moved to feb 24

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-02.jsx

Closes #805 
- Add February 2023 newsletter

Add February 2023 newsletter

---

members/members/AlexCovone.ts

[Add your profile to our Members Page!](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13)
Added Alex Covone to Virtual Coffee's member page!

Added AlexCovone

---

members/members/aishwaryamali.ts

#13 
Here are the changes made to my profile:
- updated LinkedIn and Twitter usernames

Updated profile links

---

app/routes/__frontend/resources/virtual-coffee/coding-questions-guide.mdx

Closes #815 
- Add Nick's Lunch & Learn links to Before Asking Question section
- Edit background color

Add Resources to Before Asking Question section

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-03.jsx

Closes #825 
- Add March 2023 newsletter

Add March 2023 newsletter

---

app/routes/__frontend/resources/developer-health/burnout.mdx
app/routes/__frontend/resources/developer-health/index.mdx

Closes #813 
* created separate burnout.mdx file
* moved content related to burnout in its own file

Separate Burnout from Developer Health

---

members/members/damonholden.ts

docs: add damonholden to members page

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-04.jsx

Closes #843  
- Add April 2023 newsletter

Add April 2023 newsletter

---

README.md

Update monthly challenge directions on readme

---

app/routes/__frontend/resources/virtual-coffee/guide-to-vc.mdx

Issue #855
Added The Pack Hunt description to Coffee Table Groups section of guide to VC
@danieltott 
- Keep list updated as new groups are added.

docs: add The Pack Hunt to Coffee Table Groups

---

app/root.tsx
app/routes/__frontend/index.tsx

- Update tagline and SEO description

Update tagline and description

---

app/data/monthlyChallenges/pairing-challenge.ts
app/routes/__frontend/monthlychallenges/index.tsx

- Added `current:true` to pairing challenge
- Added a progress bar to the pairing challenge on the page

Add challenge data to pairing session

---

app/routes/__frontend/resources/virtual-coffee/guide-to-vc.mdx

#858 
Added Transcending the CisTem description to Coffee Table Groups section of guide to VC
@danieltott
Keep list updated as new groups are added.

docs: add Transcending the CisTem

---

members/members/kingahmedino.ts

#13 
Added kingahmedino.ts file to be rendered on members page.

Added kingahmedino to members

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-05.jsx

Closes #874 
- Add May 2023 newsletter

Add May 2023 newsletter

---

app/routes/__frontend/resources/virtual-coffee/guide-to-vc.mdx

Closes #879 
* Updated styles for heading

Updated heading styles for Transcending the CisTem

---

members/members/chelseaerinavery.ts

#13 
Added new member profile chelseaerinavery

Added chelseaerinavery member file

---

.github/DISCUSSION_TEMPLATE/advent-of-code-2022.yml
.github/DISCUSSION_TEMPLATE/css-battles.yml
.github/DISCUSSION_TEMPLATE/open-source.yml

Trying to debug Virtual-Coffee/.github#6

Testing Discussion Category Form

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-06.jsx

Closes #914 
- Add June 2023 newsletter
- Minor fix in May 2023 newsletter

Add June 2023 newsletter

---

app/routes/__frontend/resources/virtual-coffee/guide-to-vc.mdx

Remove Transcending the CisTem
#912
Remove inactive group from Coffee Table Groups section of Guide to VC

docs: remove Transcending the CisTem

---

app/routes/__frontend/podcast/index.tsx

Update pod lead text to match the RSS feed

Update content for pod intro

---

app/routes/__frontend/monthlychallenges/index.tsx

This PR adds a new challenge called "Build in Public" to the monthly challenges page. The challenge encourages participants to communicate their work, show their development, and be proud of their progress. The description of the challenge is updated to include a link to a blog post for more information. Additionally, the "Mid-Year Check-In" challenge is marked as not current.
_Generated using [OpenSauced](https://opensauced.ai/)._## Linked Issue

Change monthly challenge

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-07.jsx

Closes #930 
- Add July 2023 newsletter.

Add July 2023 newsletter

---

members/members/danielrendox.ts

#13 
Added myself to the virtual coffee by creating `members/members/danielrendox.ts` file, according to the [instruction](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13). Thanks :)

Add me to the members page, please

---

app/routes/__frontend/monthlychallenges/index.tsx

Closes #951 
This PR updates the current monthly challenge. What have done here:
- Set "Healthy Habits" to `current: true`.
- Removed `current: true` from "Building in Public".
- Add paragraph in "Healthy Habits" to include a link to a blog post.
https://deploy-preview-952--virtual-coffee-io.netlify.app/monthlychallenges

Update monthly challenge

---

CONTRIBUTING.md

This Pull Request proposes a small modification on wording change in CONTRIBUTING.md.
Changed current phase "we ask for patience if you don't see a response immediately" to "we ask for your patience if you don't receive a response immediately". This modification provides more direct engagement with the user and clarifies the meaning of the message.

Change wording in patience request phrase

---

app/routes/__frontend/resources/virtual-coffee-handbook/join-virtual-coffee/index.mdx

Closes #940 
Fix wording on how to receive invite in `join-virtual-coffee`.
From:
> If you are interested in joining Virtual Coffee, you can join the waiting list or receive an invite from **a current member**. Once we've accepted and added you to our membership, you will receive an email with links to our Coffees.
To:
> If you are interested in joining Virtual Coffee, you can join the waiting list or receive an invite from **an active volunteer**. Once we've accepted and added you to our membership, you will receive an email with links to our Coffees.

Fix wording on how to receive invite

---

app/routes/__frontend/resources/virtual-coffee-handbook/guides-to-virtual-coffee/giving-back-to-the-community.mdx
app/routes/__frontend/resources/virtual-coffee-handbook/guides-to-virtual-coffee/keeping-up-with-virtual-coffee.mdx

Closes #943 
- Removed links from the titles in the `keeping-up-with-virtual-coffee.md`.
- Moved links from the titles to the content in the `giving-back-to-the-community,md`.
- Added link to glossary for some words in the `giving-back-to-the-community,md`.

Move Links from Titles to Content in Resources

---

CONTRIBUTING.md
README.md

Closes #946 
- Update the link that redirected back to README with the correct links.
- Update the links that redirected to 404 with the correct links.

Update Links in the README.md and CONTRIBUTING.md

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-07.jsx
app/routes/__frontend/newsletter/issues/2023-08.jsx

Closes #953 
This PR adds August 2023 newsletter onto the website.
- Added August 2023 newsletter.
- Updated `newsletters.ts`.
- Fix a typo in July 2023 newsletter.
https://deploy-preview-954--virtual-coffee-io.netlify.app/newsletter/issues/2023-08

Add August 2023 newsletter

---

app/routes/__frontend/resources/virtual-coffee-handbook/get-involved/paths-to-leadership.mdx

Closes #964 
This PR changes the title of Coffee Coordinator to Coffee Host, updates the details to match the details of Coffee Host, and gives minor fix — give space to the buttons' classNames.
https://deploy-preview-967--virtual-coffee-io.netlify.app/resources/virtual-coffee-handbook/get-involved/paths-to-leadership#coffee-host

Add the Coffee Host role and remove the Coffee Coordinator role

---

members/members/nickytonline.ts

I can create an issue if you like, but it's just my profile info updates.
I have a new domain, nickyt.co, so updating my profile info accordingly.

chore: updated some of my profile information

---

app/routes/__frontend/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups.mdx
app/routes/__frontend/resources/virtual-coffee-handbook/guides-to-virtual-coffee/slack-channels-guide.mdx

- Closes #962 
- Closes #963 
This PR updates:
- Slack channel's name from `community-questions` to `questions-about-vc`.
- Sunday's Accountabillibuddies leader from Raynald to Ethan.

Update a Slack channel's name and Sunday's Accountabilibuddies leader

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/sept-2023.jsx

N/A
This PR adds September monthly challenge to the website.
Changes in this PR:
- Created `sept-2023.jsx` in the `monthlychallenges` folder.
- Updated the `getChallenges.ts`.
- Set "Preptember" to `current: true` and remove `current: true` from "Healthy Habit".
https://deploy-preview-978--virtual-coffee-io.netlify.app/monthlychallenges/sept-2023

Add September 2023 Monthly Challenge

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-09.jsx

Closes #979  
This PR adds September 2023 newsletter onto the website.
- Added September 2023 newsletter.
- Updated `newsletters.ts`.

Add September 2023 newsletter

---

members/members/terieyenike.ts

Feat: profile info details (teri)

---

members/members/jamescurran.ts

https://github.com/Virtual-Coffee/virtualcoffee.io/issues/995
Added my Profile file (with location)
In order to form a more perfect union.

Added JamesCurran profile file

---

members/members/aishwaryamali.ts

#995 
- Added Hacktoberfest2023 badge 
- Added my location to Member profile
Looked up my latitude/longitude on google maps and then pasted it in.

Added Hacktoberfest2023 badge and my location to member profile

---

members/core/danieltott.ts

- https://github.com/Virtual-Coffee/virtualcoffee.io/issues/995
I added my location to my member profile file using latitude and longitude.
Looked up my lat/long on google maps and then pasted it in while everyone watched.

Added my location to my member profile

---

members/members/YufaLi.ts

- https://github.com/Virtual-Coffee/virtualcoffee.io/issues/995
- Added my member profile and location

Added my member profile and location

---

members/members/Satoshi-Sh.ts

- #13 
- #1004 
Added my profile file with a geo-location.

Added Satoshi-Sh

---

members/dakim
members/members/dakim.ts

#995
Add David Akim to members.
Followed instructions
Agreed to code of conduct.

Add david akim to members

---

members/members/jdwilkin4.ts

#995 
This PR is responsible for updating my website field for my profile as well as adding my location entry for the map.
These changes are part of the hacktoberfest 2023 VC challenge. 

chore: updating jdwilkin4 profile and adding location on the map

---

README.md

fix typo in Resources section of README.m

---

members/members/chrisjin.ts

- https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13
- https://github.com/Virtual-Coffee/virtualcoffee.io/issues/995
Added my profile (chrisjin) to member profile files. Added location as well. 
Looked up my location coordinates through google maps. 

added chrisjin to members and added location object

---

members/members/wheeleruniverse.ts

https://github.com/Virtual-Coffee/virtualcoffee.io/issues/995
* created wheeleruniverse.ts file under the members directory
* updated wheeleruniverse.ts file to include required fields
* updated wheeleruniverse.ts file to include location field
- used Google Maps to find lat/lng for my approximate location

added me (wheeleruniverse) to members

---

members/members/nickytonline.ts

Relates to #995
Adds nickytonline's longitude and latitude coordinates to their member profile.

chore: add nickytonline's longitude & latitude

---

members/members/HpatricioH.ts

#13 
#995 
I added my profile to the member profile files, also I included my location in my file.
Looked up my location coordinates using latlong finder.

Added HpatricioH to the member list

---

app/routes/__frontend/monthlychallenges/oct-2023.jsx

N/A
This PR updates content in the October challenge page as follow:
- Changed a section title "Weekly async check-ins" to "Weekly check-ins".
- Updated the content by adding Friday sync check-ins and adjusted the section accordingly.
- Added Julia to facilitators.
- Updated descriptions in some recommended repos.
https://deploy-preview-1016--virtual-coffee-io.netlify.app/monthlychallenges/oct-2023

Update content in October challenge page

---

members/members/adiati98.ts

- https://github.com/Virtual-Coffee/virtualcoffee.io/issues/995
This PR updates Ayu's member profile with:
- Hacktoberfest2023 badge
- Location

chores: Update Ayu's profile for Hacktoberfest 2023

---

members/members/ARodriguezHacks.ts

Adding my GH profile, ARodriguezHacks, to the members page.
Changes necessary to continue being part of the community and being up-to-date on my membership.

Add Angie (ARodriguezHacks) to members

---

members/members/Arol15.ts

#13 
#995 
- Added `Arol15.ts` file to the members' directory
- Updated `Arol15.ts` to include `badges` and `location` categories
- followed the example set by the community

Add new member with badge and location 

---

members/members/anshumanSathua.ts

#13 
#995 
- Added member profile
- Added the hacktoberfest badge and my location to the member profile
Looked up my latitude/longitude on latlong.net and then pasted it in.

created my member profile

---

members/members/shiftyp.ts

#995 
Added location for myself
Followed instructions

Added location for shiftyp

---

members/members/christinaLoiacono.ts

#995 
Added location for myself
Followed instructions

Add new member Christina and location

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-10.jsx

Closes #1018 
This PR adds October 2023 newsletter to the website and updates the `newsletters.ts`.
As a note for future newsletters, the changes here are including semantic HTML corrections.
https://deploy-preview-1025--virtual-coffee-io.netlify.app/newsletter/issues/2023-10

feat: Add October 2023 Newsletter

---

members/core/tkshill.ts

Adding to Membership map

---

members/members/mikestreety.ts

Add profile as per pinned issue

Add mikestreety user profile

---

members/core/bekahhw.ts

Update member profile with location

---

members/members/BrennaKH.ts

Add Brenna's profile to member page

---

members/members/piotrszymaniec.ts

- #13
- #995
Added member file for Piotr Szymaniec profile

Add Piotr Szymaniec member profile

---

members/members/tammymiller.ts

Add Tammy Miller to the members pages with location included

---

members/members/raaynaldo.ts

Add Raynaldo Sutisna to Members

---

members/members/iotalex.ts

Add Iotalex profile to our Members Page! #13

---

members/members/funbunch.ts

Added the profile for funbunch

Adding member profile

---

members/members/dominicduffin1.ts

#995
Update existing profile and add location data for Dominic Duffin

Update Dominic Duffin profile

---

members/members/michaeljolley.ts

Adding Michael Jolley to members

Adding Michael Jolley to members

---

members/members/iotalex.ts

Add yourself to our member map! #995

---

app/routes/__frontend/monthlychallenges/oct-2023.jsx

N/A
This PR adds newly added VC-verified repositories to the list in October challenge page on the website.
https://deploy-preview-1057--virtual-coffee-io.netlify.app/monthlychallenges/oct-2023

chores: Add VC-Verified Repositories to the List in October Challenge Page

---

members/members/evagracesmith.ts

added my profile

---

app/routes/__frontend/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups.mdx

N/A
As per update by @meg-gutshall, this PR updates the current leaders and the times for Accountabilibuddies coffee table group.
This PR also removes Marie from the Tech Interview Studies Group leader.
https://deploy-preview-1066--virtual-coffee-io.netlify.app/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups#accountabilibuddies

Update Accountabilibuddies Leaders and Times

---

members/members/shraddha.ts

#13
This PR adds my profile as a member to the virtual coffee team.

Add member profile

---

members/members/mikerogers0.ts

Remove website link from @MikeRogers0's member profile as the domain has expired. 😞 

Remove defunct website link

---

members/members/megGutshall.ts

Update member profile

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2023-11.jsx

Closes #1083 
This PR adds November 2023 newsletter to the website and updates the `newsletters.ts`.
https://deploy-preview-1084--virtual-coffee-io.netlify.app/newsletter/issues/2023-11

feat: Add November 2023 newsletter to the website

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/dec-2023.jsx
app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/nov-2023.tsx

Closes #1092 
This PR adds December 2023 challenge onto the webpage with details as follow:
- Added `dec-2023.jsx` --> copied and updated from `app/routes/__frontend/monthlychallenges/dec-2022.jsx`.
- Updated `monthlychallenges/index.tsx` with current challenge.
- Updated `data/monthlyChallenges/getChallenges.ts`.
- Added the alert of challenge is complete in `app/routes/__frontend/monthlychallenges/nov-2023.tsx`
Monthly challenges page:
https://deploy-preview-1093--virtual-coffee-io.netlify.app/monthlychallenges
December challenge page:
https://deploy-preview-1093--virtual-coffee-io.netlify.app/monthlychallenges/dec-2023

Add December 2023 Challenge

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/dec-2023.jsx
app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/jan-2024.jsx

Closes #1103 
This PR adds newly challenge: New Year, New Goals with below details:
- Created `jan-2024.jsx` and added content.
- Added the new challenge to `app\routes\__frontend\monthlychallenges\index.tsx` and set it to `current: true`.
- Updated `getChallenges.ts`
- Added challenge completed alert to the December challenge.
- **Monthly Challenges page**: https://deploy-preview-1104--virtual-coffee-io.netlify.app/monthlychallenges
- **January 2024 page**: https://deploy-preview-1104--virtual-coffee-io.netlify.app/monthlychallenges/jan-2024

docs: Add January 2024 challenge

---

members/members/codewithjazzy.ts

#13 
This PR adds my profile as a member to the virtual coffee team
N/A

Added my profile to the Members Page

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2024-01.jsx

Closes #1106 
This PR adds January 2024 newsletter to the website and updates the `newsletters.ts`.
https://deploy-preview-1107--virtual-coffee-io.netlify.app/newsletter/issues/2024-01

feat: Add January 2024 newsletter to the website

---

members/members/danvgar.ts

[https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13)

Added danvgar profile and map location

---

members/members/danielrendox.ts

#995
- add my location
- update bio
- add LinkedIn

Update my info on member page

---

app/routes/__frontend/monthlychallenges/feb-2024.jsx
app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/jan-2024.jsx

Closes #1125 
This PR adds February 2024 challenge (Month of Learning) to the website with changes as follow:
1. In the `app/routes/__frontend/monthlychallenges/index.tsx`:
2.  In the `app\routes\__frontend\monthlychallenges`:
**Monthly challenge page**
https://deploy-preview-1126--virtual-coffee-io.netlify.app/monthlychallenges
**February challenge page**
https://deploy-preview-1126--virtual-coffee-io.netlify.app/monthlychallenges/feb-2024

Docs: Add February 2024 challenge to the website

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2024-03.jsx

Closes #1136  
This PR adds March 2024 newsletter to the website and updates the `newsletters.ts`.
https://deploy-preview-1137--virtual-coffee-io.netlify.app/newsletter/issues/2024-03

Add March 2024 newsletter to the website

---

members/members/derekjj.ts
members/teams.ts

Adding Derek to members

---

members/members/nazislam.ts

Adding github profile

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2024-04.jsx

Closes #1148 
This PR adds April 2024 newsletter to the website and updates the `newsletters.ts`.
https://deploy-preview-1149--virtual-coffee-io.netlify.app/newsletter/issues/2024-04

Add April 2024 newsletter to the website

---

app/routes/__frontend/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups.mdx

Closes #1150 
This PR updates the Coffee Table Group details with the following:
- Removed the Sunday session and leader from Accountabilibuddies
- Updated the Feelings Friday time from 10 AM to 8 PM ET.
- Removed the Saturday session and leader from Frontend Friday Folks and adjusted the description.
https://deploy-preview-1151--virtual-coffee-io.netlify.app/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups

Docs: Update Coffee Table Groups

---

app/routes/__frontend/monthlychallenges/index.tsx

Add blog post to monthly challenge index

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2024-05.jsx

Closes #1174 
This PR adds April 2024 newsletter to the website and updates the `newsletters.ts`.
https://deploy-preview-1175--virtual-coffee-io.netlify.app/newsletter/issues/2024-05

Add May 2024 newsletter to the website

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/june-2024.jsx
app/routes/__frontend/monthlychallenges/may-2024.jsx

Closes #1184 
This PR adds June 2024 challenge (Mid-Year Check-In) to the website.
https://deploy-preview-1185--virtual-coffee-io.netlify.app/monthlychallenges

Add June monthly challenge

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2024-06.jsx

Closes #1189 
This PR adds April 2024 newsletter to the website and updates the `newsletters.ts`.
https://deploy-preview-1190--virtual-coffee-io.netlify.app/newsletter/issues/2024-06

Add June 2024 newsletter to the website

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/july-2024.jsx
app/routes/__frontend/monthlychallenges/june-2024.jsx

Closes #1196 
This PR adds July 2024 challenge (Welcoming Community) to the website.
https://deploy-preview-1197--virtual-coffee-io.netlify.app/monthlychallenges
https://deploy-preview-1197--virtual-coffee-io.netlify.app/monthlychallenges/july-2024

Add July 2024 Monthly Challenge

---

app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/july-2024.jsx

Relates to #1196 
This PR adds a blog post for July 2024 challenge and updates wording in the challenge page.

Add a blog post to July 2024 challenge

---

app/components/NewslettterSubscribe.tsx

#1191 
This pull request updates the subscription form to use the new Beehiiv subscription link instead of the old Mailchimp link.
The change was necessary to ensure that new subscribers are directed to the correct subscription service (Beehiiv) as we have moved away from using Mailchimp. The form's `action` URL was updated to reflect the new URL as stated in the issue.

Update newsletter subscription link

---

members/teams.ts

add Derek to the list of coffee table host for pack hunt

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2024-07.jsx

Closes #1202 
This PR adds July 2024 newsletter to the website and updates the data in the `newsletters.ts` file.
https://deploy-preview-1203--virtual-coffee-io.netlify.app/newsletter/issues/2024-07

Add July 2024 newsletter to the website

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/aug-2024.jsx
app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/july-2024.jsx

Closes #1209 
- Adds the August 2024 Monthly Challenge page to the site.
- Updates the current Monthly Challenge to August 2024.
To be merged 8/1 or evening 7/31.

Update Monthly Challenge from July to August

---

app/routes/__frontend/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups.mdx

I made the long-needed changes on the website. This updates the list to reflect what's current and adds historical groups as well.

Update coffee-table-groups.mdx File

---

app/data/monthlyChallenges/getChallenges.ts
app/routes/__frontend/monthlychallenges/aug-2024.jsx
app/routes/__frontend/monthlychallenges/index.tsx
app/routes/__frontend/monthlychallenges/sept-2024.jsx

Closes #1215 
This PR adds September 2024 challenge (Preptember) to the website.
https://deploy-preview-1216--virtual-coffee-io.netlify.app/monthlychallenges
https://deploy-preview-1216--virtual-coffee-io.netlify.app/monthlychallenges/sept-2024

Add Sept 2024 Monthly Challenge

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2024-08.jsx

Closes #1217 
This PR adds August 2024 newsletter to the website and updates the data in the `newsletters.ts` file.
https://deploy-preview-1218--virtual-coffee-io.netlify.app/newsletter/issues/2024-08

Add August 2024 newsletter to the website

---

app/data/newsletters.ts
app/routes/__frontend/newsletter/issues/2024-09.jsx

Closes #1221 
This PR adds September 2024 newsletter to the website and updates the data in the `newsletters.ts` file.
https://deploy-preview-1222--virtual-coffee-io.netlify.app/

Add September 2024 newsletter to the website

---

src/app/monthlychallenges/(challenges)/oct-2024/page.tsx
src/app/monthlychallenges/(challenges)/sept-2024/page.tsx
src/app/monthlychallenges/page.tsx

Closes #1228 
This PR adds September 2024 challenge (Hacktoberfest) to the website.

feat: Add October 2024 Challenge to the Website

---

src/components/Nav.tsx

added "Join" nav-link under navbar component before the "Store" nav-link with 
href="/resources/virtual-coffee-handbook/join-virtual-coffee"

Closes #1182

---

src/app/monthlychallenges/(challenges)/oct-2024/page.tsx

Fixes #1238 
This PR updates Slack channels that we will use during VCHI challenge.

fix: Update Slack channels for VCHI in the challenge page

---

src/content/members/core/megGutshall.ts

#1240 
Add Hacktoberfest 2024 badge to my profile

Add Hacktoberfest 2024 badge

---

src/content/members/members/christinaLoiacono.ts

#1240
Add Hacktoberfest 2024 badge for Christina, and update bio.
I followed Dan's instructions from the Hacktoberfest Kickoff event!

Add Hacktoberfest 2024 badge for Christina

---

src/content/members/members/ThanhCorn.ts

Add Hacktoberfest 2024 badge for ThanhCorn

---

src/content/members/members/ClJarvis.ts

#1240 This is for 2024 VC update
I added a badge and updated social links.

updating C Jarvis profile

---

src/content/members/members/funbunch.ts

Added new badge. 
Updating for this year's Hacktober.

Adding 2024 badge to funbunch.ts

---

src/content/members/members/Jenna59.ts

member profile

---

src/content/members/members/Jenna59.ts

Hacktoberfest Badge Ticket

---

src/content/members/members/adiati98.ts

#1240
This PR adds Hacktoberfest 2024 badge to Ayu Adiati's profile.

feat: Add Hacktoberfest 2024 badge

---

src/content/newsletters/2024-10.jsx
src/data/newsletters.ts

Closes #1274 
This PR adds September 2024 newsletter to the website and updates the data in the `newsletters.ts` file.

Add October 2024 newsletter to the website

---

src/content/members/members/nubrin.ts

#13 
Hello! After attending Virtualcoffee on last thursday, I was told that I would be added to the slack channel and that I can add my profile in github but I still have not yet received the invitation, So I am trying to see if I can be added in the slack channel and my profile be added in the github.
Yes. I Accept.

Added my profile nubrin.ts

---

src/content/newsletters/2024-11.jsx
src/data/newsletters.ts

Closes #1290 
This PR adds November 2024 newsletter to the website and updates the data in the `newsletters.ts` file.

Add November 2024 newsletter to the website

---

src/app/monthlychallenges/page.tsx

#1273
Fixed the apostrophe character in the Healthy Habits text. 
Link: https://virtualcoffee.io/monthlychallenges 
Please scroll down and look for (Healthy Habits for Happy Devs) section.
Before:
Now:
Just Updated the text

fixed the apostrophe character in the Healthy Habits text

---

src/content/newsletters/2024-12.jsx
src/data/newsletters.ts

Closes #1301 
This PR adds December 2024 newsletter to the website and updates the data in the `newsletters.ts` file.

Add December 2024 newsletter to the website

---

src/app/monthlychallenges/(challenges)/dec-2024/page.tsx
src/app/monthlychallenges/(challenges)/jan-2025/page.tsx
src/app/monthlychallenges/page.tsx

Closes #1307 
This PR adds January 2025 challenge (New Year, New Goal) to the website.
Blog post link will be added once it's published on DEV. Currently, it's still a draft.
**Monthly Challenge Homepage**
https://deploy-preview-1308--virtual-coffee-io.netlify.app/monthlychallenges
**January 2025 Page**
https://deploy-preview-1308--virtual-coffee-io.netlify.app/monthlychallenges/jan-2025

feat: Add January 2025 Challenge to the Website

---

src/app/monthlychallenges/(challenges)/spring-2025/page.tsx

Closes #1324 
This PR fixes a typo and changes the word "quarterly" to "quarter".

fix: Change "quarterly" to "quarter"

---

src/app/newsletter/page.tsx

Fixes #1306 
We want to keep newsletters that are manually written on the website. This PR changes the wording from "Current Issues" to "Archived Newsletters" in the newsletter page to indicate that.
https://deploy-preview-1323--virtual-coffee-io.netlify.app/newsletter

fix: Change wording for archived newsletters

---

src/content/members/teams.ts
src/content/resources/virtual-coffee-handbook/get-involved/paths-to-leadership.mdx
src/content/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups.mdx

Closes #1337 
Remove references to Abbey as CTG Coordinator so other members can volunteer for the role

Remove references to Abbey as CTG Coordinator

---

src/app/monthlychallenges/page.tsx
src/content/resources/virtual-coffee-handbook/get-involved/paths-to-leadership.mdx
src/content/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups.mdx

Closes #1354 
David Akim is no longer able to host Accountabilibuddies on Tuesday nights and Eddie has not had steady attendance for Tech Interview Study Group. We're seeking a new lead for Tech Interview Study Group and moving the Accountabilibuddies session to Monday afternoons with Eddie and Rad co-hosting.

1354 update coffee table groups page

---

src/app/monthlychallenges/(challenges)/may-2025/page.tsx
src/app/monthlychallenges/(challenges)/summer-2025/page.tsx
src/app/monthlychallenges/page.tsx

Closes #1347 
This PR holds the below changes:
- Add `summer-2025/page.tsx` for the "Summer 2025 Bi-Month Challenge: Get Job Ready"
- Update the challenge homepage for the current challenge
- Add completed challenge banner to the `page.tsx` in may-2025.
https://deploy-preview-1348--virtual-coffee-io.netlify.app/monthlychallenges

Add "Summer 2025 Bi-Month Challenge: Get Job Ready" to the website

---

src/content/members/members/devanshukoli.ts

#13 
- I have followed as per the issue link description. and added my profile into this `src/content/members/members/` path.
- I am member of virutal-coffee and recently the talk in the slack channel got my attention and then I visited the *members* page. There I saw that every member from virutal-coffee is part of this page. So I would also like to become one. and see myself there. :)

[add]: My profile (Devanshukoli)

---

src/content/members/members/alanacapcreates.ts

Linked to: #13 Add to Members Page 
Finally adding myself as an ~official member of the VC community
All the basic bio info was added

[add] Alana Caporale to members list

---

src/content/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups.mdx

Closes #1371 
Removes Eddie as Accountabilibuddies Host and removes DSA Office Hours CTG from active list

1371 docs remove eddie

---

CODEOWNERS

Add Super Contributor permissions

---

src/app/monthlychallenges/(challenges)/aug-2025/page.tsx
src/app/monthlychallenges/(challenges)/summer-2025/page.tsx
src/app/monthlychallenges/page.tsx

Closes #1373 
This PR holds the below changes:
- Add `aug-2025/page.tsx` for the "August 2025: Photography Challenge"
- Update the challenge homepage for the current challenge
- Add completed challenge banner to the `page.tsx` in summer-2025.
https://deploy-preview-1374--virtual-coffee-io.netlify.app/monthlychallenges

Add August 2025: Photography Challenge to the website

---

src/content/resources/virtual-coffee-handbook/guides-to-virtual-coffee/coffee-table-groups.mdx

Closes #1380
Remove Monday Accountabilibuddies Session

Update CTG list

---

README.md
src/app/monthlychallenges/(challenges)/aug-2025/page.tsx
src/app/monthlychallenges/(challenges)/fall-2025/page.tsx
src/app/monthlychallenges/page.tsx

This pull request updates the monthly challenges page to highlight the current challenge and updates the "Preptember" challenge. It also removes outdated documentation about managing newsletters from the `README.md`. The key changes are as follows:
* Marked "Preptember" as the current challenge by setting `current: true` and removed the `current: true` flag from the "Photography Challenge" to ensure only one challenge is marked as current at a time. [[1]](diffhunk://#diff-64346fcf6132d142802ac41dab7b2b4817493c832a08e1115b118bb83aa65acfR290-R298) [[2]](diffhunk://#diff-64346fcf6132d142802ac41dab7b2b4817493c832a08e1115b118bb83aa65acfL646)
* Enhanced the "Preptember" challenge's subtitle and description to better explain its purpose and structure, emphasizing skill-building and preparation …

feat: fall 2025 challenge

---

src/content/members/members/Shubham404.ts

* created a file Shubham404.ts at /src/content/members/members/
* renamed object export to Shubham404 (no hyphens)
* added details like githubUsername, linkedinUsername, websiteURL, profileMask.
* added location.
to add Shubham-404 to VC's members page adhering to guidelines at [issue #13](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13)

add Shubham404 to members page

---

src/content/members/members/pedaars.ts

#1403
Add emoji and update badges for Aaron Pedwell
Update my profile as described in the issue

Add emoji and update badges for Aaron Pedwell

---

src/content/members/core/bekahhw.ts

feat: add Hacktoberfest2025 badge to bekahhw profile
